---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install terminal tools
    package:
      name:
        - htop
        - tmux
        - vim

  - name: copy wallpapers
    copy:
      src: files/wallpapers/*
      dest: /usr/share/backgrounds
      owner: root
      group: root

  - name: set wallpaper
    become_user: simbaclaws
    dconf:
      key: "/org/gnome/desktop/background/picture-uri"
      value: "'file:///usr/share/backgrounds/flat-wallpapers/wallpaper27.jpg'"

  - name: set wallpaper position
    become_user: simbaclaws
    dconf:
      key: "/org/gnome/desktop/background/picture-options"
      value: "'zoom'"
      