---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install terminal tools
    package:
      name:
        - htop
        - tmux
        - vim

  - name: get flat-wallpapers
    git:
      repo: 'https://github.com/Simbaclaws/flat-wallpapers.git'
      dest: /usr/share/backgrounds
      owner: root
      group: root

  - name: get linux-wallpapers
    git:
      repo: 'https://github.com/Simbaclaws/linux-wallpapers.git'
      dest: /usr/share/backgrounds
      owner: root
      group: root

  - name: get star-citizen-wallpapers
    git:
      repo: 'https://github.com/Simbaclaws/star-citizen-wallpapers.git'
      dest: /usr/share/backgrounds
      owner: root
      group: root

  - name: get nature-wallpapers
    git:
      repo: 'https://github.com/Simbaclaws/nature-wallpapers.git'
      dest: /usr/share/backgrounds
      owner: root
      group: root

  - name: set wallpaper
    become_user: simbaclaws
    dconf:
      key: "/org/gnome/desktop/background/picture-uri"
      value: "'file:///usr/share/backgrounds/flat-wallpapers/wallpaper27.jpg'"

  - name: set wallpaper position
    become_user: simbaclaws
    dconf:
      key: "/org/gnome/desktop/background/picture-options"
      value: "'zoom'"
      