- name: users | hylke | remove preinstalled clutter from home directory
  file:
    path: /home/hylke/{{ item }}
    state: absent
  with_items:
    - examples.desktop
    - Desktop
    - Documents
    - Downloads
    - Music
    - Pictures
    - Public
    - Templates
    - Videos

- name: users | hylke | create personal config directories
  tags: dotfiles,dotfiles-hylke
  file:
    path: /home/hylke/{{ item.dir }}
    state: directory
    owner: hylke
    group: hylke
    mode: 0700
  with_items:
    - { dir: .config }
    - { dir: .config/autostart }
    - { dir: .config/bpytop }
    - { dir: .config/gtk-3.0 }
    - { dir: .local }
    - { dir: .local/share }
    - { dir: .local/share/applications }
    - { dir: bin }
    - { dir: desktop }
    - { dir: documents }
    - { dir: downloads }
    - { dir: projects }
    - { dir: templates }

- name: users | hylke | copy user-dirs.dirs
  tags: dotfiles,dotfiles-hylke
  copy:
    src: users/hylke/user-dirs.dirs
    dest: /home/hylke/.config/user-dirs.dirs
    owner: hylke
    group: hylke
    mode: 0600
  notify: update_xdg

# - name: users | hylke | copy personal config files
#   tags: dotfiles,dotfiles-hylke
#   copy:
#     src: users/hylke/{{ item.src }}
#     dest: /home/hylke/{{ item.dest }}
#     owner: hylke
#     group: hylke
#     mode: 0600
#   with_items:
#     - { src: 'asunder', dest: '.asunder' }
#     - { src: 'bpytop.conf', dest: '.config/bpytop/bpytop.conf' }
#     - { src: 'directory_bookmarks', dest: '.config/gtk-3.0/bookmarks' }
#     - { src: 'gvimrc', dest: '.gvimrc' }
#     - { src: 'linode-cli', dest: '.config/linode-cli' }
#     - { src: 'mimeapps.list', dest: '.config/mimeapps.list' }
#     - { src: 'ssh_client_config', dest: '.ssh/config' }
#     - { src: 'terminator_config', dest: '.config/terminator/config' }

- name: users | hylke | copy profile image
  tags: dotfiles,dotfiles-hylke
  copy:
    src: users/hylke/profile_image.jpeg
    dest: /var/lib/AccountsService/icons/hylke.png
    owner: root
    group: root
    mode: 0644