- name: users | hylke | set user
  tags: hylke,sudo,users
  user:
    name: hylke
    group: hylke
    groups: adm,ansible,{{sudo_group}}
    state: present
    comment: "Hylke Hellinga"
    shell: /bin/bash

- name: users | hylke | create .ssh directory
  tags: dotfiles,hylke,ssh,users
  file:
    path: "{{ item.dir }}"
    state: directory
    owner: hylke
    group: hylke
    mode: 0700
  with_items:
    - { dir: '/home/hylke/.ssh' }

- name: users | hylke | create config directories
  tags: dotfiles,hylke,tmux,users,vim,zsh
  file:
    path: /home/hylke/{{ item.dir }}
    state: directory
    owner: hylke
    group: hylke
    mode: 0700
  with_items:
    - { dir: '.bash' }
    - { dir: '.config' }
    - { dir: '.config/htop' }
    - { dir: '.config/mc' }
    - { dir: '.tmux' }
    - { dir: '.tmux/config' }
    - { dir: '.tmux/plugins' }
    - { dir: '.vim' }
    - { dir: '.vim/autoload' }
    - { dir: '.vim/bundle' }
    - { dir: '.vim/colors' }
    - { dir: '.vim/ftplugin' }
    - { dir: '.zsh' }

# - name: users | hylke | copy dotfiles
#   tags: dotfiles,users,hylke,tmux,users,vim,zsh
#   copy:
#     src: users/hylke/{{ item.src }}
#     dest: /home/hylke/{{ item.dest }}
#     owner: hylke
#     group: hylke
#     mode: 0600
#   with_items:
#     - { src: 'bash/bash_aliases', dest: '.bash/bash_aliases' }
#     - { src: 'bash/bash_profile', dest: '.bash_profile' }
#     - { src: 'bash/bash_prompt', dest: '.bash/bash_prompt' }
#     - { src: 'bash/bash_functions', dest: '.bash/bash_functions' }
#     - { src: 'bash/bashrc', dest: '.bashrc' }
#     - { src: 'bash/profile', dest: '.profile' }
#     - { src: 'git/gitconfig', dest: '.gitconfig' }
#     - { src: 'htop/htoprc', dest: '.config/htop/htoprc' }
#     - { src: 'inputrc', dest: '.inputrc' }
#     - { src: 'mc/mc.ini', dest: '.config/mc/ini' }
#     - { src: 'vim/vimrc', dest: '.vimrc' }
#     - { src: 'zsh/zshrc', dest: '.zshrc' }

# - name: users | hylke | clone tmux-completion plugin repository
#   tags: dotfiles,hylke,users,tmux
#   git:
#     repo: https://github.com/srsudar/tmux-completion.git
#     dest: /home/hylke/.tmux/plugins/completion
#     force: yes
#   notify: update_tmux_plugin_perms

# - name: users | hylke | clone tmux-continuum plugin repository
#   tags: dotfiles,hylke,users,tmux
#   git:
#     repo: https://github.com/tmux-plugins/tmux-continuum
#     dest: /home/hylke/.tmux/plugins/continuum
#     force: yes
#   notify: update_tmux_plugin_perms

# - name: users | hylke | clone tmux-resurrect plugin repository
#   tags: dotfiles,hylke,users,tmux
#   git:
#     repo: https://github.com/tmux-plugins/tmux-resurrect
#     dest: /home/hylke/.tmux/plugins/resurrect
#     force: yes
#   notify: update_tmux_plugin_perms

# - name: users | hylke | copy individual zsh config files
#   tags: dotfiles,hylke,users,zsh
#   copy:
#     src: users/hylke/zsh/{{ item.src }}
#     dest: /home/hylke/.zsh/{{ item.src }}
#     owner: hylke
#     group: hylke
#     mode: 0600
#   with_items:
#     - { src: 'aliases.zsh' }
#     - { src: 'bindkey.zsh' }
#     - { src: 'completion.zsh' }
#     - { src: 'exports.zsh' }
#     - { src: 'functions.zsh' }
#     - { src: 'history.zsh' }
#     - { src: 'path.zsh' }
#     - { src: 'plugins.zsh' }
#     - { src: 'prompt.zsh' }
#     - { src: 'setopt.zsh' }
#     - { src: 'theming.zsh' }

# - name: users | hylke | copy vim ftype files
#   tags: dotfiles,hylke,users,vim
#   copy:
#     src: users/hylke/vim/{{ item.src }}
#     dest: /home/hylke/.vim/ftplugin/{{ item.src }}
#     owner: hylke
#     group: hylke
#     mode: 0600
#   with_items:
#     - { src: 'cmake.vim' }
#     - { src: 'cpp.vim' }
#     - { src: 'html.vim' }
#     - { src: 'perl.vim' }
#     - { src: 'python.vim' }
#     - { src: 'ruby.vim' }
#     - { src: 'sql.vim' }
#     - { src: 'xml.vim' }

# - name: users | hylke | copy vim color files
#   tags: dotfiles,hylke,users,vim
#   copy:
#     src: users/hylke/vim/{{ item.src }}
#     dest: /home/hylke/.vim/colors/{{ item.src }}
#     owner: hylke
#     group: hylke
#     mode: 0600
#   with_items:
#     - { src: 'bubblegum-256-dark.vim' }
#     - { src: 'darktango.vim' }
#     - { src: 'jellybeans.vim' }
#     - { src: 'xoria256.vim' }
#     - { src: 'zenburn.vim' }

# - name: users | hylke | install pathogen
#   tags: dotfiles,hylke,users,vim
#   copy:
#     src: users/hylke/vim/{{ item.src }}
#     dest: "{{ item.dest }}"
#     owner: hylke
#     group: hylke
#     mode: 0700
#   with_items:
#     - { src: 'pathogen.vim', dest: '/home/hylke/.vim/autoload/pathogen.vim' }

# - name: users | hylke | checkout git repositories
#   tags: git,users,hylke
#   become: yes
#   git:
#     repo: "{{ item.repo }}"
#     dest: "{{ item.dest }}"
#     force: yes
#   with_items:
#     - { repo: 'https://github.com/ctrlpvim/ctrlp.vim.git', dest: '/home/hylke/.vim/bundle/ctrlp.vim' }
#     - { repo: 'https://github.com/davidhalter/jedi-vim.git', dest: '/home/hylke/.vim/bundle/jedi-vim' }
#     - { repo: 'https://github.com/pearofducks/ansible-vim', dest: '/home/hylke/.vim/bundle/ansible-vim' }
#     - { repo: 'https://github.com/rhysd/vim-grammarous.git', dest: '/home/hylke/.vim/bundle/vim-grammarous' }
#     - { repo: 'https://github.com/ron89/thesaurus_query.vim', dest: '/home/hylke/.vim/bundle/thesaurus_query' }
#     - { repo: 'https://github.com/scrooloose/nerdtree.git', dest: '/home/hylke/.vim/bundle/nerdtree' }
#     - { repo: 'https://github.com/tpope/vim-obsession.git', dest: '/home/hylke/.vim/bundle/vim-obsession' }
#     - { repo: 'https://github.com/vim-syntastic/syntastic.git', dest: '/home/hylke/.vim/bundle/syntastic' }
#   notify: update_vim_bundle_perms