## Full System Upgrade
- name: Display all variables/facts known for a host
  ansible.builtin.debug:
    var: hostvars[inventory_hostname]
    verbosity: 4

- name: system setup | full upgrade
  yum:
    name: '*'
    state: latest
  when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['ansible_distribution_major_version'] == '7'

- name: system setup | full upgrade
  dnf:
    name: '*'
    state: latest
  when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['ansible_distribution_major_version'] == '8'

- name: system setup | full upgrade
  dnf:
    name: '*'
    state: latest
  when: ansible_facts['ansible_distribution'] == 'Fedora' and ansible_facts['ansible_distribution_major_version'] | int >= 22

- name: system setup | full upgrade
  yum:
    name: '*'
    state: latest
  when: ansible_facts['ansible_distribution'] == 'Fedora' and ansible_facts['ansible_distribution_major_version'] | int < 22

- name: system setup | full upgrade
  apt:
    name: '*'
    state: latest
  when: ansible_facts['os_family'] == 'Debian'

- name: system setup | full upgrade
  pacman:
    name: '*'
    state: latest
  when: ansible_facts['os_family'] == 'Archlinux'
