## Full System Upgrade
- name: system setup | full upgrade
  yum:
    name: '*'
    state: latest
  when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] == '7'

- name: system setup | full upgrade
  dnf:
    name: '*'
    state: latest
  when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] == '8'

- name: system setup | full upgrade
  apt:
    name: '*'
    state: latest
  when: ansible_facts['os_family'] == 'Debian'

- name: system setup | full upgrade
  pacman:
    name: '*'
    state: latest
  when: ansible_facts['os_family'] == 'Archlinux'
